[Actions] Updated .github/actions/dotnet/action.yml

diff --git a/.github/actions/dotnet/action.yml b/.github/actions/dotnet/action.yml
--- a/.github/actions/dotnet/action.yml
+++ b/.github/actions/dotnet/action.yml
@@ -92,23 +92,18 @@ runs:
       working-directory: ${{github.workspace}}/src
       shell: bash
       run: |
-        dotnet restore \
+        r=5
+        delay=30
+        until dotnet restore \
               --warnaserror \
               -nodeReuse:False \
               -p:NoWarn=MSB4241 \
-              -p:SuppressNETCoreSdkPreviewMessage=true || \
-        dotnet restore \
-              --warnaserror \
-              -nodeReuse:False \
-              -p:NoWarn=MSB4241 \
-              -p:SuppressNETCoreSdkPreviewMessage=true \
-              --ignore-failed-sources || \
-        dotnet restore \
-              --warnaserror \
-              -nodeReuse:False \
-              -p:NoWarn=MSB4241 \
-              -p:SuppressNETCoreSdkPreviewMessage=true \
-              --ignore-failed-sources
+              -p:SuppressNETCoreSdkPreviewMessage=true
+        do
+          ((--r)) || exit 1
+          echo "⚠️ Restore failed, retrying in ${delay}s ($r attempt(s) left)"
+          sleep "${delay}"
+        done
 
     - name: "Dotnet: Build"
       working-directory: ${{github.workspace}}/src
@@ -122,6 +117,7 @@ runs:
                   "-p:EnableSarif=True" \
                   "-p:IsProduction=${{inputs.production-build}}" \
                   "-p:NoWarn=MSB4241" \
+                  "-p:Optimize=true" \
                   "-p:SuppressNETCoreSdkPreviewMessage=true" \
                   "-p:Version=${{inputs.build-version}}" \
                   -nodeReuse:False
@@ -144,6 +140,7 @@ runs:
                   --ignore-exit-code 8 \
                   --report-github \
                   "-p:ContinuousIntegrationBuild=true" \
+                  "-p:EnableSarif=True" \
                   "-p:IsProduction=${{inputs.production-build}}" \
                   "-p:NoWarn=MSB4241" \
                   "-p:Optimize=true" \
